function Add-EAGAppClientSecret {
	<#
	.SYNOPSIS
		Adds a client secret to an App Registration.
	
	.DESCRIPTION
		Adds a client secret to an App Registration.
		The secret value is automatically generated by the API and returned as result from this command.
		The secret can never again be retrieved, after this comman completes, so make sure you handle the result object.
	
	.PARAMETER ObjectId
		The ObjectID of the App Registration to add a client secret to.
		
	.PARAMETER ApplicationId
		The ApplicationID (ClientID) of the App Registration to add a client secret to.
	
	.PARAMETER DisplayName
		The name of the secret to add.
	
	.PARAMETER Start
		Starting when the secret is valid.
		Defaults to "now"
	
	.PARAMETER End
		Until when the secret is valid.
		Defaults to "2 years after Start"
	
	.PARAMETER AppCache
		A hashtable cache of App Registrations to optimize request performance.
		For each authentication method piped to this command, first the App Registration is looked up, if not in this cache.
		With this parameter, you can perform the caching across multiple separate invocations.
	
	.PARAMETER ServiceMap
		Optional hashtable to map service names to specific EntraAuth service instances.
        Used for advanced scenarios where you want to use something other than the default Graph connection.
        Example: @{ Graph = 'GraphBeta' }
        This will switch all Graph API calls to use the beta Graph API.

	.PARAMETER WhatIf
		If this switch is enabled, no actions are performed but informational messages will be displayed that explain what would happen if the command were to run.
	
	.PARAMETER Confirm
		If this switch is enabled, you will be prompted for confirmation before executing any operations that change state.
	
	.EXAMPLE
		PS C:\> Add-EAGAppClientSecret -ApplicationId bdcc7469-e495-451a-8618-4a57aace4b74

		Adds a client secret to the specified application.

	.EXAMPLE
		PS C:\> Get-EAGAppRegistration -DisplayName 'CAF-PS-BootcampDemo' | Add-EAGAppClientSecret -DisplayName "Test Secret" -Start (Get-Date) -End (Get-Date).AddDays(666)

		Adds a "Test Secret" Client Secret to the App Registration named 'CAF-PS-BootcampDemo'.
		It is valid for the next 666 days.
	#>
	[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingConvertToSecureStringWithPlainText", "")]
	[CmdletBinding(SupportsShouldProcess = $true, DefaultParameterSetName = 'Identity')]
	param (
		[Parameter(Mandatory = $true, ParameterSetName = 'Identity', ValueFromPipelineByPropertyName = $true)]
		[Alias('Id')]
		[string]
		$ObjectId,

		[Parameter(Mandatory = $true, ParameterSetName = 'Filter', ValueFromPipelineByPropertyName = $true)]
		[Alias('AppId', 'ClientID')]
		[string]
		$ApplicationId,

		[string]
		$DisplayName,

		[DateTime]
		$Start,

		[DateTime]
		$End,

		[hashtable]
		$AppCache = @{ },

		[hashtable]
		$ServiceMap = @{}
	)
	begin {
		$services = $script:serviceSelector.GetServiceMap($ServiceMap)

		Assert-EntraConnection -Service $services.Graph -Cmdlet $PSCmdlet
	}
	process {
		#region Resolve App Registration to use
		$appResolved = Resolve-Application -ObjectId $ObjectId -ApplicationId $ApplicationId -Unique -Cache $AppCache -Services $services
		if (-not $appResolved.Success) {
			Invoke-NonTerminatingException -Cmdlet $PSCmdlet -Message $appResolved.Message -Category ObjectNotFound -Target "$($ApplicationId)$($ObjectId)"
			return
		}
		$currentApp = $appResolved.Result
		#endregion Resolve App Registration to use

		Write-Verbose "Adding Client Secret '$DisplayName' to App Registration '$($currentApp.DisplayName)' ($($currentApp.AppID))"
		if (-not $PSCmdlet.ShouldProcess("$($currentApp.DisplayName) ($($currentApp.AppID))", "Adding Client Secret '$DisplayName'")) { return }

		$body = @{
			passwordCredential = @{}
		}
		if ($DisplayName) { $body.passwordCredential.displayName = $DisplayName }
		if ($Start) { $body.passwordCredential.startDateTime = $Start.ToUniversalTime().ToString('u') -replace ' ', 'T' }
		if ($End) { $body.passwordCredential.endDateTime = $End.ToUniversalTime().ToString('u') -replace ' ', 'T' }
		if ($body.passwordCredential.Count -lt 1) { $body = @{} }

		try {
			$result = Invoke-EntraRequest -Service $services.Graph -Method POST -Path "applications/$($currentApp.Id)/addPassword" -ContentType 'application/json' -Body $body -WarningAction SilentlyContinue
		}
		catch {
			$PSCmdlet.ThrowTerminatingError($_)
		}

		# Protect the secret value, before passing it through
		$secret = $result.secretText | ConvertTo-SecureString -AsPlainText -Force
		$result.secretText = $secret
		[PSCustomObject]@{
			PSTypeName  = 'EntraAuth.Graph.Application.AppAuthentication'
			AppID       = $currentApp.AppID
			AppName     = $currentApp.DisplayName
			Type        = 'Secret'
			Name        = $result.displayName
			Info        = '{0:yyyy-MM-dd HH:mm:ss} -> {1:yyyy-MM-dd HH:mm:ss}' -f $result.startDateTime, $result.endDateTime
			Identity    = $result.keyId
			Data        = $result
			SecretValue = $secret
		}
	}
}